#!/bin/bash
# This is a installer for installing required packages

# possibly need to apt-get install subversion

# File to run installation of the cloud search system
echo ""
echo "1: Installing pip..." 
sudo apt-get update
sudo apt-get -y install python-pip python-dev
sudo pip install pip --upgrade


echo ""
echo "Installing python packages..."
sudo pip install psutil CherryPy 
sudo apt-get -y install python-dateutil python-pyparsing #python-pypcap python-dpkt
sudo apt-get -y install python-scapy


echo ""
echo "Installing ZeroMQ..."
sudo apt-get -y install build-essential uuid-dev libtool autoconf automake
mkdir "libs"
pushd libs
wget http://download.zeromq.org/zeromq-3.2.4.tar.gz
tar -zxvf zeromq-3.2.4.tar.gz
pushd "zeromq-3.2.4"
./configure
make
sudo make install
sudo ldconfig
popd
popd
echo "Installing PyZmq"
sudo pip install pyzmq


echo ""
echo "Installing mongodb..."
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
sudo apt-get update
sudo apt-get -y install mongodb-10gen

sudo sudo pip install pymongo



echo ""
echo "creating a default config.cfg file ..."
pushd "NetworkSearch2"
cp configTemplate.cfg config.cfg
popd
echo "Installation completed."
echo "Note : please configure the NetworkSearch2/config.cfg file before run a search node"
